"""create initial tables

Revision ID: 59f4d1b06602
Revises: 
Create Date: 2026-07-29 13:19:02.665316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f4d1b06602'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('enquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='enquiry_status'), nullable=False),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiries_email'), 'enquiries', ['email'], unique=False)
    op.create_index('ix_enquiries_status_created_at', 'enquiries', ['status', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_enquiry_id'), 'audit_logs', ['enquiry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        op.f('ix_audit_logs_enquiry_id'),
        table_name='audit_logs'
    )
    op.drop_index(
        op.f('ix_audit_logs_created_at'),
        table_name='audit_logs'
    )
    op.drop_index(
        op.f('ix_audit_logs_admin_id'),
        table_name='audit_logs'
    )

    op.drop_table('audit_logs')

    op.drop_index(
        'ix_enquiries_status_created_at',
        table_name='enquiries'
    )
    op.drop_index(
        op.f('ix_enquiries_email'),
        table_name='enquiries'
    )

    op.drop_table('enquiries')

    # PostgreSQL enum type must also be removed
    sa.Enum(
        name='enquiry_status'
    ).drop(
        op.get_bind(),
        checkfirst=True
    )

    op.drop_index(
        op.f('ix_admins_email'),
        table_name='admins'
    )

    op.drop_table('admins')